name: Functional Tests
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
jobs:
  functional-tests:
    runs-on:
      group: github-v1
    env:
      CC: gcc
    steps:
      - name: Install ausearch for debugging seccomp/bad syscalls
        run: sudo apt update && sudo apt install -y auditd

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.73.0

      - uses: ./.github/actions/deps

      - name: Build everything
        run: make -j -Otarget fddev

      - name: Run single transaction
        run: |
          max_attempts=10
          attempt=1
          while ! ./src/test/single-transaction.sh; do
              echo "Attempt $attempt failed, retrying..."
              ((attempt++))
              if (( attempt > max_attempts )); then
                  echo "Maximum attempts reached. Exiting."
                  exit 1
              fi
          done

      - name: Run single transfer
        run: |
          max_attempts=10
          attempt=1
          while ! ./src/test/single-transfer.sh; do
              echo "Attempt $attempt failed, retrying..."
              ((attempt++))
              if (( attempt > max_attempts )); then
                  echo "Maximum attempts reached. Exiting."
                  exit 1
              fi
          done

  script-tests:
    runs-on:
      group: github-v1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.73.0

      - uses: ./.github/actions/deps
      - uses: ./.github/actions/hugepages

      - name: Build
        run: make -j -Otarget

      - name: Run functional tests
        run: make -j -Otarget run-script-test
